### PR TITLE
Update Eigen source but in new branch

### PR DESCRIPTION
**Pull request by maximecharriere**
In [Pull 77](https://github.com/STORM-IRIT/OpenGR/pull/77) I had just modify the file `.gitmodules` in master branch without a fork and new branch.
This time I did it right.

### CODE REVIEW

**Comment by nmellado** [comment]
Could you please rebase on top of master ? The CI failed last time.

**Comment by maximecharriere** [comment]
I'm sorry but I'm not an expert with git yet.  
It seems to me that I have rebase `maximecharriere:eigenSource` on top of `STORM-IRIT:master`, but I'm not 100% confident.
I have done the following commande. 
```bash
git pull upstream master
git checkout eigenSource
git rebase master 
```
(upstream point to https://github.com/STORM-IRIT/OpenGR.git)

If I have done something wrong, I'm listening.

**Comment by nmellado** [comment]
Hum, it looks like your rebase has failed (would have been better to do `git rebase -i upstream/master` (I don't know if your local master has upstream linked to OpenGR or your fork).
Anyway, a simple way to fix this is to create a new local branch from upstream master, cherry-pick your commit. In order to keep that PR, you can force-push this local branch to the remove `EigenSource` branch (when calling set-upstream).

**Comment by maximecharriere** [comment]
I did your tricks, and now EigenSource is realy on top of master. It should work.
OpenGr tree

On the other hand I don't know why the compilation tests don't pass.

**Comment by nmellado** [comment]
The commit number used for the submodule is not available in this new repository: https://github.com/STORM-IRIT/OpenGR/pull/82/checks#step:6:60
Can you try with the commit id of the current master of Eigen ? Can be an opportunity to update.

**Comment by maximecharriere** [comment]
And here we go, the tests pass !

**Review by nmellado — APPROVED** [review]

**Comment by nmellado** [comment]
Thanks, nice.

**Pull request merged**
