### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by sgiraudot**
We detected some warnings from the [CGAL testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-100/Point_set_processing_3_Examples/TestReport_Friedrich_Ubuntu-gcc-7.gz), here are the fixes (I'm not sure which branch is the best to fix them, we use `v1.2.0-rc` in our testsuite, so I figured I should make a PR on this branch).

### CODE REVIEW

**Comment by sloriot** [comment]
@nmellado what is the recommended branch for users?

**Comment by nmellado** [comment]
Hi,
Sorry, `v1.2.0-rc` should have been removed, it was a working branch, the last release merged to master was on branch `v1.2.0-rc`.
Please use `master` as base branch for PRs and users.

**Comment by sloriot** [comment]
@maxgimeno didn't you say that the master branch was breaking the CGAL testuite?

**Comment by maxGimeno** [comment]
I thought so, at least. I'll put it back on our testsuite, we'll see.

**Comment by nmellado** [comment]
Let me know when you switched to `master`, I'll remove this obsolete branch.

**Comment by sgiraudot** [comment]
Alright, we redid the testsuite using master, [some warnings pop up](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-104/Point_set_processing_3_Examples/TestReport_Friedrich_Ubuntu-gcc-7.gz) and I completely remade this branch to fix them.

**Pull request merged**
